micronaut:
  application:
    name: keymanagerRest

grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    keymanager-grpc:
      address: ${GRPC_URL:`localhost:50051`}
      plaintext: true
      max-retry-attempts: 10