version: '3'
services:
  bcb:
    image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-bcb-pix"
    ports:
      - 8082:8082

  erp-itau:
    image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-itau-erp"
    ports:
    - 9091:9091

  keymanager-mysql:
    image: 'mysql:5.7'
    container_name: keymanager-mysql
    expose:
      - 3306
    ports:
      - 13306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=pix
      - MYSQL_ROOT_HOST=%

  keymanager-grpc:
    depends_on:
      - keymanager-mysql
    container_name: keymager-grpc
    image: keymanager-grpc.jar
    ports:
      - 50051:50051
    environment:
      ITAU_URL: http://erp-itau:9091
      BCB_URL: http://bcb:8082
      BD_HOST: keymanager-mysql
      BD_PASSWORD: root

  keymanager-rest:
    depends_on:
      - keymanager-grpc
      - keymanager-mysql
    container_name: keymager-rest
    image: keymanager-rest.jar
    ports:
      - 8080:8080
    environment:
      GRPC_URL: keymanager-grpc:50051
